### ISSUE TITLE
Change `docutils literal notranslate` color

### ISSUE THREAD

**Issue by akaszynski** [ansys/ansys-sphinx-theme#118]
`class="docutils literal notranslate"` looks pink, and I've never really liked the color scheme. Nothing against pink, but I don't feel it belongs in technical documentation (nor would something like red unless in a big bold warning).

![tmp](https://user-images.githubusercontent.com/11981631/188175257-87a29faa-7142-4ae7-8180-3a3e04592a13.png)

**Comment by akaszynski** [comment]
cc @PipKat for her expertise.

**Comment by PipKat** [comment]
@akaszynski The pink was chosen because so many of the Python packages we reference use this color for literal tags--and it passed accessibility checks for readability in dark and light modes. @Revathyvenugopal162, I will let Tim Duffy, our UX expert know that Alex would like to see us use something else that also passes the accessibility checks. I couldn't tag Tim here, but I'll chat him the information.

**Comment by akaszynski** [comment]
Thanks @PipKat. Ideally something that's not link color (blue) or a header color (black, matches text).

**Comment by PipKat** [comment]
@akaszynski I relayed this to Tim--but if you want inline literal tags be black text in a gray box, just like in code, Revathy can probably just implement it. We wouldn't have to wait for Tim's input. @Revathyvenugopal162?

**Comment by PipKat** [comment]
@akaszynski @Revathyvenugopal162  Tim said that he thought we had already agreed to use black text in a gray box for literal tagging. I told him that we discussed so much in that meeting, all I clearly remember is that we all agreed that we didn't want to keep the gold! Anyhow, @Revathyvenugopal162, feel free to change the font color to black. Thanks!
