### ISSUE TITLE
Problems with "Edit" links

### ISSUE THREAD

**Issue by RobPasMue** [ansys/ansys-sphinx-theme#141]
Looks like the edit link color theme is "white" in light mode, which makes it invisible to bare eye. In dark mode it is working properly though. Could we look into it?

See https://dev.geometry.docs.pyansys.com/

Light mode: 
![image](https://user-images.githubusercontent.com/37798125/198005570-15882a0f-bbc5-4bd5-97dd-b5e73b878cdf.png)
![image](https://user-images.githubusercontent.com/37798125/198005512-ff9e09e8-92b5-4c0c-b165-2f85742235c1.png)

Dark mode:
![image](https://user-images.githubusercontent.com/37798125/198005428-5a44de57-ed98-4861-8b2f-7ed2f90fc414.png)

**Comment by germa89** [comment]
hahahaha.. I just came to post the same issue! xD

**Comment by germa89** [comment]
I would also add that the ``Edit links`` return 404 when you use it on Gallery examples or autogenerated functions/classes.

**Comment by RobPasMue** [comment]
Examples should work @germa89. Check on PyGeometry just in case.

**Comment by MaxJPRey** [comment]
I noticed the same issue as @germa89 .

**Comment by Revathyvenugopal162** [comment]
If we are generating examples with sphinx gallery, it will give an error page, since the example pages are generated from a python module, but in pygeometry it is different, we are not generating examples notebook with sphinx gallery, instead we are directly proving the notebook, so it will give an edit link to the examples in pygeometry.

**Comment by RobPasMue** [comment]
Has this already been solved with #143 @Revathyvenugopal162? If that's the case, please close this issue.
