### ISSUE TITLE
Gallery thumbnails are too small

### ISSUE THREAD

**Issue by pkrull-ansys** [ansys/ansys-sphinx-theme#181]
This was a problem encountered in pyadditive. The tiles in the gallery are too small and one of the titles gets cut off. I've tried adding a .css file according to the sphinx-gallery docs, [Configuration — Sphinx-Gallery 0.11.1-git documentation](https://sphinx-gallery.github.io/stable/configuration.html#setting-gallery-thumbnail-size), but it doesn't have any effect. This can be seen at https://additive.docs.pyansys.com/dev/examples/index.html.

**Comment by Revathyvenugopal162** [comment]
There is no blocking configuration with ansys sphinx theme to add additional css file and update the styles for libs. We have to update the conf file to read the additions css files . Below is the updated page(locally) with the above configuration as per sphinx-gallery docs, if this is the preferred layout, we can update the ansys-sphinx-theme which will reflect in all libs, pinging here @MaxJPRey for the visibility. otherwise i can setup a css file exclusively for pyadditive (if so, please let me know offline). 
![image](https://user-images.githubusercontent.com/104772255/213697487-ebd4faef-ede4-4db3-b4c4-c5e679dc2d26.png)

**Comment by pkrull-ansys** [comment]
@Revathyvenugopal162 What you show is exactly what I want. I'm ok with either updating the theme or using a css file for pyadditive. Whichever you guys think is best. I tried creating my own css file but must have misunderstood the docs. If you could share your file, that would be great! Thanks! 
@MaxJPRey

**Comment by MaxJPRey** [comment]
Adding @RobPasMue , @jorgepiloto for visibility.

**Comment by RobPasMue** [comment]
I think it's mainly a matter of how you configure your "matrix" view for the gallery... If you want 5-8 elements on each row, then the thumbnails will for sure be very small. However, if you give it more space (3-4 elements per row) images will look better without having to configure it using the CSS https://mapdl.docs.pyansys.com/dev/examples/index.html

I'm not an expert on configuring Sphinx-Gallery but I do think that if you still want to go with the CSS option, it should be repo-specific (i.e. @Revathyvenugopal162 just pass the CSS file to @pkrull-ansys and that's it).

**Comment by MaxJPRey** [comment]
I agree with @RobPasMue . Let's try to keep this repo (`ansys-sphinx-theme`) as generic as possiblt and if a custom *.CSS is needed, then we offer the opportunity for each team and projects to have their own.
This way they can update it as often as needed without any dependencies with this current repo. It should guaranty flexibility.
Otherwise it could become difficult to maintain this repo with all the custom *.CSS files.

**Comment by pkrull-ansys** [comment]
What I'm puzzled about is I don't see CSS files in other repositories, for instance `pymapdl`, yet the gallery layout is better. I've compared `conf.py` in both `pymapdl` and `pyadditive` and don't see anything affecting gallery thumbnails that's different between the two unless there's an indirect effect I'm not aware of. @Revathyvenugopal162 please send me whatever you did to get the layout better.

**Comment by pkrull-ansys** [comment]
@Revathyvenugopal162 Disregard my request. I figured out what I was missing when I tried to implement the CSS file previously.

**Comment by pkrull-ansys** [comment]
Closing this issue.
