### ISSUE TITLE
Make collapse_navigation True

### ISSUE THREAD

**Issue by akaszynski** [ansys/ansys-sphinx-theme#194]
Given how many PyAnsys repositories have deep nested APIs, let's consider simply collapsing the navigation by default as done in: https://github.com/pyansys/pyaedt/pull/2434

This helps to avoid the issue seen here:
![dmp](https://user-images.githubusercontent.com/11981631/217166654-8643b705-9b70-433f-aac0-b9f8af279d3c.png)

Link:
https://fluent.docs.pyansys.com/release/0.12/api/meshing/datamodel/workflow/index.html

---

Side note: 
The horizontal scroll bar is just out of reach in the sidebar navigation and you have to scroll down for it. Let's either submit a PR to [pydata-sphinx-theme](https://github.com/pydata/pydata-sphinx-theme) or fix it in our CSS.

**Comment by jorgepiloto** [comment]
Thanks for suggesting this, @akaszynski.

Let us proceed the same way we did to enable default values for the HTML theme options and declare this configuration in [this line](https://github.com/ansys/ansys-sphinx-theme/blob/main/src/ansys_sphinx_theme/__init__.py#L63).

Also, I like the idea proposed by @greschd some days ago about removing the whole namespace in the documentation headers. This is a consequence of our `_templates/class.rst`, I think.

This would simplify a lot the left navigation bar. The image above these lines would present an structure like:

```console
meshing
|- tui
|- datamodel
|  |- workflow
|     |- Workflow
|     |- TaskObject
...
```

Instead of:

```console
meshing
|- meshing.tui
|- meshing.datamodel
|  |- meshing.datamodel.workflow
|     |- meshing.datamodel.workflow.Workflow
|     |- meshing.datamodel.workflow.TaskObject
...
```

In fact, it is also possible to display the whole namespace in the documentation for each object, so the sidebar gets less clutered but information is still present in the docs.

**Comment by Revathyvenugopal162** [comment]
We can alter class.rst to create obj name instead of full name in autosummary, but still at some point, we need to make the scrollbar visible. It is already implemented in[ pydpf-composite](https://composites.dpf.docs.pyansys.com/release/0.1/api/_autosummary/ansys.dpf.composites.constants.FailureOutput.html)

**Comment by RobPasMue** [comment]
> 
> This would simplify a lot the left navigation bar. The image above these lines would present an structure like:
> 
> ```
> meshing
> |- tui
> |- datamodel
> |  |- workflow
> |     |- Workflow
> |     |- TaskObject
> ...
> ```

I think that's a good approach. I've been complaining about this for some time now. Thanks for bringing it up @jorgepiloto
