### ISSUE TITLE
Unify the PyAnsys landing page for libs

### ISSUE THREAD

**Issue by Revathyvenugopal162** [ansys/ansys-sphinx-theme#499]
Different libs in the PyAnsys have different layout for landing page.
Making a uniform layout will be better for all the libs

example:
- https://geometry.docs.pyansys.com/version/stable/index.html 
- https://mapdl.docs.pyansys.com/version/dev/index.html 

Issue initially reported by @jorgepiloto 
Pinging @mia-guo-ux as we discussed in private

**Comment by mia-guo-ux** [comment]
Hi @Revathyvenugopal162 @jorgepiloto 
I suggest using a 3-column layout on home pages. 
![image](https://github.com/user-attachments/assets/cf66dd2f-5ac2-4080-9304-92eb55eade3d)
![image](https://github.com/user-attachments/assets/19a16d14-8e5a-4b5e-a835-30176a6f9668)


In addition, the following improvements could be considered:

**Standardizing the icons in each card, or remove the icons completely.**
- For example, whenever the card is about "Examples", we can use the same icon on different homepages (i.e. using the icon on PyMAPDL and PyAnsys Geometry examples cards)
![image](https://github.com/user-attachments/assets/24e4626c-3c6f-4dd5-b3bb-d6bdad5eea8c)


**Keeping a consistent naming and description convention.**
- Currently, cards on the two homepages have different naming styles. The card headers of PyMAPDL seem to be short phrases starting with a verb, where card headers of Geometry are much shorter, with 1 or 2 verbs/nouns. I prefer the latter one because it is simpler. 

- PyMAPDL (screenshot from the website)
![image](https://github.com/user-attachments/assets/fce5188f-cf80-4aa2-8083-e67074d1f908)

- Geometry (screenshot from the website)
![image](https://github.com/user-attachments/assets/6be894e9-6499-4d0c-baff-43b5f06fe1ed)

- The screenshots above provide updated card headers on PyMAPDL and feel free to change the card header to whatever summarize the page content. 


**Arranging the cards on homepages in an order that is as consistent as possible. We can start with crucial and technical cards and end with social or style guide cards.**

- The screenshots above show the updated card order. Please feel free to rearrange the cards in a way that you think would help the users read and understand the content.

**Comment by greschd** [comment]
> I suggest using a 3-column layout on home pages.

I think these should reduce to two, then one column as the viewport gets narrower (e.g. on phones) when the original 3 no longer fit.

**Comment by mia-guo-ux** [comment]
> > I suggest using a 3-column layout on home pages.
> 
> Detail: I think these should reduce to two, then one column as the viewport gets narrower (e.g. on phones) when the original 3 no longer fit.

We have the 3-column layout on PyAnsys homepage too. I also found this layout on other Ansys web products. For smaller screens, we can have several breakpoints so once a certain screen size is reached, we change the layout.

**Comment by MaxJPRey** [comment]
That would be great to set those so we fit most of the screens.

**Comment by jorgepiloto** [comment]
@mia-guo-ux Are we dropping logos in the landing page? Should we request some unified set of logos too?

**Comment by RobPasMue** [comment]
I wouldn't drop the logos - but I would standardize their usage for sure (Logo XYZ corresponds to ABC on all our docs). This is currently not the case - each repo uses their preferred logos at the moment.

**Comment by davegouger** [comment]
Some other inconsistencies I've been noticing when working on PySTK and comparing to other PyAnsys sites:

**Site title**
Title conventions are inconsistent across the libraries. Some use the PyAnsys library logo:
![image](https://github.com/user-attachments/assets/0b97c5b7-78df-4163-a2fe-09b5d5adf330)

Some sites have a title as such:
![image](https://github.com/user-attachments/assets/c7725295-9661-46b1-9d60-f965f05e88eb)

**Landing page intros**
Some sites include a brief intro about the PyAnsys library, some include lengthy descriptions that span a good portion of the page, and others do not include an intro at all. 

It would be great for all of these to be fairly consistent to have a unified feel.

**Comment by RobPasMue** [comment]
Hi @davegouger! You are completely right. Ideally, all libraries should have a logo but not all of them have it. Meaning that the fallback mechanism (in that case is having the title). We might have to work with marketing to get a logo for each and one of our libraries to standarize it. I think the logos look much better anyway.

And yes, we should standarize the intros. Ideally there should be no text (or almost no text). Cards should do the job to redirect you to the area you want.

**Comment by jorgepiloto** [comment]
Let's update the landing page of our theme docs according to this, @Revathyvenugopal162.
